import type {Metadata} from 'next';
import '../../theme/global.tailwind.css';
import {NextIntlClientProvider} from 'next-intl';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
type Props = {
  children: React.ReactNode;
};
export default function RootLayout({children}: Props) {
  return (
    <html lang="en">
      <NextIntlClientProvider>
        <body>{children}</body>
      </NextIntlClientProvider>
    </html>
  );
}
