import type {Metadata} from 'next';

import {NextIntlClientProvider} from 'next-intl';
import {getMessages, setRequestLocale} from 'next-intl/server';
import type {ReactNode} from 'react';
import type {AppLocale} from '@/i18n/locales';
import {defaultLocale} from '@/i18n/locales';
import Providers from './providers';

import '@/theme/global.tailwind.css';

export const metadata: Metadata = {
  title: 'Once for all',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
  params: {
    locale: AppLocale;
  };
};

export default async function RootLayout({children, params}: Props) {
  const locale = params?.locale ?? defaultLocale;

  if (!params?.locale) {
    console.warn(
      `[RootLayout] Missing locale param. Falling back to default "${defaultLocale}".`
    );
  }

  setRequestLocale(locale);

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
