import type {Metadata} from 'next';
import '../../theme/global.tailwind.css';
import {NextIntlClientProvider} from 'next-intl';
export const metadata: Metadata = {
  title: 'Once for all',
  description: 'Generated by create next app',
};
type Props = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};
export default function RootLayout({children, params}: Props) {
  const {locale} = params;
  return (
    <html lang={locale}>
      <NextIntlClientProvider>
        <body>{children}</body>
      </NextIntlClientProvider>
    </html>
  );
}
